### ISSUE TITLE
importing tls_client fails with "dependency missing error", even though it is present

### ISSUE THREAD

**Issue by Raduan77** [FlorianREGAZ/Python-Tls-Client#16]
Hey, I am facing next error, when trying to import tls_client:
```
>>> import tls_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/tls_client/__init__.py", line 15, in <module>
    from .sessions import Session
  File "/usr/local/lib/python3.9/site-packages/tls_client/sessions.py", line 1, in <module>
    from .cffi import request
  File "/usr/local/lib/python3.9/site-packages/tls_client/cffi.py", line 15, in <module>
    library = ctypes.cdll.LoadLibrary(f'{root_dir}/dependencies/tls-client{file_ext}')
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.9/site-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory
```
I checked, and I definitely have this file downloaded(I can even open it with normal `with open(...)` statement.

Also, ran ctypes library separately:
```
>>> import ctypes
>>> library = ctypes.cdll.LoadLibrary('/usr/local/lib/python3.9/site-packages/tls_client/dependencies/tls-client-amd64.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.9/site-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory
```

same issue. Any ideas on how to fix this? I am running this code on docker python:3.9 image on m1 macbook.

when I run it not in docker, everything works perfectly.

**Comment by Raduan77** [comment]
seems like the same issue as in https://github.com/FlorianREGAZ/Python-Tls-Client/issues/13
```
in docker:
>>> from platform import machine
>>> machine()
'aarch64'
```
