### ISSUE TITLE
cannot unmarshal array into Go struct field RequestInput.headers of type string

### ISSUE THREAD

**Issue by FuckingToasters** [FlorianREGAZ/Python-Tls-Client#22]
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/infinimonster/Documents/Privat/Python/discordphoneverify/new version/main.py", line 145, in verify
    checktoken()
  File "/home/infinimonster/Documents/Privat/Python/discordphoneverify/new version/main.py", line 135, in checktoken
    response = session.get(url="https://discord.com/api/v9/users/@me", headers=HEADERS, proxy=proxyauth if proxytype != "" else None)
  File "/home/infinimonster/.local/lib/python3.10/site-packages/tls_client/sessions.py", line 364, in get
    return self.execute_request(method="GET", url=url, **kwargs)
  File "/home/infinimonster/.local/lib/python3.10/site-packages/tls_client/sessions.py", line 347, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: json: cannot unmarshal array into Go struct field RequestInput.headers of type string

**Comment by SlotthCode** [comment]
What is your discord?

**Comment by FuckingToasters** [comment]
> What is your discord?

Infinimonster#0002

I fixed this issue however it would be nice if this lib can add async support
