### ISSUE TITLE
Encountered an error

### ISSUE THREAD

**Issue by pengyanbing84** [FlorianREGAZ/Python-Tls-Client#41]
internal buffer error : Memory allocation failed : growing buffer
fatal error: runtime: C malloc failed
goroutine 107184 [IO wait]:
internal/poll.runtime_pollWait(0x2a0f7b4b7b8, 0x72)
	/Users/bogdan/.gvm/gos/go1.18.7/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc007196370?, 0x2c?, 0x0)
	/Users/bogdan/.gvm/gos/go1.18.7/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.execIO(0xc0055fcf18, 0x7ffeabec51a0)
	/Users/bogdan/.gvm/gos/go1.18.7/src/internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).Read(0xc0055fcf00, {0xc006314000, 0xc2e4, 0xc2e4})
	/Users/bogdan/.gvm/gos/go1.18.7/src/internal/poll/fd_windows.go:441 +0x25f
net.(*netFD).Read(0xc0055fcf00, {0xc006314000?, 0xc005d451c0?, 0xc00631ffaa?})
	/Users/bogdan/.gvm/gos/go1.18.7/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000006298, {0xc006314000?, 0x151b?, 0xc005d451c0?})
	/Users/bogdan/.gvm/gos/go1.18.7/src/net/net.go:183 +0x45
github.com/bogdanfinn/utls.(*atLeastReader).Read(0xc0079ae690, {0xc006314000?, 0x0?, 0x2a0a3eaffff?})
	/Users/bogdan/.gvm/pkgsets/go1.18.7/global/pkg/mod/github.com/bogdanfinn/utls@v1.5.11/conn.go:791 +0x3d
bytes.(*Buffer).ReadFrom(0xc005bb02b0, {0x7ffeabf24560, 0xc0079ae690})
	/Users/bogdan/.gvm/gos/go1.18.7/src/bytes/buffer.go:204 +0x98
github.com/bogdanfinn/utls.(*Conn).readFromUntil(0xc005bb0000, {0x2a0f6764ff8?, 0xc000006298}, 0x33f?)
	/Users/bogdan/.gvm/pkgsets/go1.18.7/global/pkg/mod/github.com/bogdanfinn/utls@v1.5.11/conn.go:813 +0xe5
github.com/bogdanfinn/utls.(*Conn).readRecordOrCCS(0xc005bb0000, 0x0)
	/Users/bogdan/.gvm/pkgsets/go1.18.7/global/pkg/mod/github.com/bogdanfinn/utls@v1.5.11/conn.go:620 +0x116
github.com/bogdanfinn/utls.(*Conn).readRecord(...)
	/Users/bogdan/.gvm/pkgsets/go1.18.7/global/pkg/mod/github.com/bogdanfinn/utls@v1.5.11/conn.go:586
github.com/bogdanfinn/utls.(*Conn).Read(0xc005bb0000, {0xc0042aa000, 0x1000, 0xc001704c60?})
	/Users/bogdan/.gvm/pkgsets/go1.18.7/global/pkg/mod/github.com/bogdanfinn/utls@v1.5.11/conn.go:1300 +0x16f
bufio.(*Reader).Read(0xc001704ba0, {0xc005839c38, 0x9, 0xc006049d68?})
	/Users/bogdan/.gvm/gos/go1.18.7/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x7ffeabf24020, 0xc001704ba0}, {0xc005839c38, 0x9, 0x9}, 0x9)
	/Users/bogdan/.gvm/gos/go1.18.7/src/io/io.go:331 +0x9a
io.ReadFull(...)
	/Users/bogdan/.gvm/gos/go1.18.7/src/io/io.go:350
github.com/bogdanfinn/fhttp/http2.readFrameHeader({0xc005839c38?, 0x9?, 0xc005c6d4d0?}, {0x7ffeabf24020?, 0xc001704ba0?})
	/Users/bogdan/.gvm/pkgsets/go1.18.7/global/pkg/mod/github.com/bogdanfinn/fhttp@v0.5.14/http2/frame.go:238 +0x6e
github.com/bogdanfinn/fhttp/http2.(*Framer).ReadFrame(0xc005839c00)
	/Users/bogdan/.gvm/pkgsets/go1.18.7/global/pkg/mod/github.com/bogdanfinn/fhttp@v0.5.14/http2/frame.go:494 +0x95
github.com/bogdanfinn/fhttp/http2.(*clientConnReadLoop).run(0xc000abbfa0)
	/Users/bogdan/.gvm/pkgsets/go1.18.7/global/pkg/mod/github.com/bogdanfinn/fhttp@v0.5.14/http2/transport.go:2020 +0x165
github.com/bogdanfinn/fhttp/http2.(*ClientConn).readLoop(0xc005b56340)
	/Users/bogdan/.gvm/pkgsets/go1.18.7/global/pkg/mod/github.com/bogdanfinn/fhttp@v0.5.14/http2/transport.go:1942 +0x79
created by github.com/bogdanfinn/fhttp/http2.(*Transport).newClientConn
	/Users/bogdan/.gvm/pkgsets/go1.18.7/global/pkg/mod/github.com/bogdanfinn/fhttp@v0.5.14/http2/transport.go:821 +0xbea

goroutine 106957 [select]:
github.com/bogdanfinn/fhttp.setRequestCancel.func4()
	/Users/bogdan/.gvm/pkgsets/go1.18.7/global/pkg/mod/github.com/bogdanfinn/fhttp@v0.5.14/client.go:398 +0x8b
created by github.com/bogdanfinn/fhttp.setRequestCancel
	/Users/bogdan/.gvm/pkgsets/go1.18.7/global/pkg/mod/github.com/bogdanfinn/fhttp@v0.5.14/client.go:397 +0x439

**Comment by qoft** [comment]
no code to recreate this error?
only reason i see that could cause this is that you ran too many request threads.

**Comment by pengyanbing84** [comment]
> no code to recreate this error? only reason i see that could cause this is that you ran too many request threads.

I use multithreading for scraping. Encountered this problem. Using requests does not have this problem

**Comment by pengyanbing84** [comment]
Enable multi-threaded sending requests in multiple processes. An error was encountered. Never returned.
