### ISSUE TITLE
ARM64 support?

### ISSUE THREAD

**Issue by GYKgamer** [FlorianREGAZ/Python-Tls-Client#70]
I wanted to ask if theres arm64 support? I'm trying to run a python script but it fails because of a missing arm64 file.

2023-05-06 22:06:31.145 Uncaught app exception
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/home/pi/gpt4free/streamlit_app.py", line 7, in <module>
    from gpt4free import you
  File "/home/pi/gpt4free/gpt4free/__init__.py", line 4, in <module>
    from gpt4free import forefront
  File "/home/pi/gpt4free/gpt4free/forefront/__init__.py", line 10, in <module>
    from tls_client import Session
  File "/usr/local/lib/python3.9/dist-packages/tls_client-0.2.1-py3.9.egg/tls_client/__init__.py", line 15, in <module>
    from .sessions import Session
  File "/usr/local/lib/python3.9/dist-packages/tls_client-0.2.1-py3.9.egg/tls_client/sessions.py", line 1, in <module>
    from .cffi import request, freeMemory
  File "/usr/local/lib/python3.9/dist-packages/tls_client-0.2.1-py3.9.egg/tls_client/cffi.py", line 20, in <module>
    library = ctypes.cdll.LoadLibrary(f'{root_dir}/dependencies/tls-client{file_ext}')
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.9/dist-packages/tls_client-0.2.1-py3.9.egg/tls_client/dependencies/tls-client-arm64.so: cannot open shared object file: No such file or directory

**Comment by BlueSchnabeltier** [comment]
check out my fork it has support [python-tls-client-arm32](https://github.com/BlueSchnabeltier/python-tls-client-arm32)

**Comment by StephanAkkerman** [comment]
Check if the file is missing from the directory. If it is, download `tls-client-arm64.so` from https://github.com/FlorianREGAZ/Python-Tls-Client/tree/master/tls_client/dependencies and it should work.
